# Generated by Django 5.1.7 on 2025-03-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predicted_images/')),
                ('class_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
