# Generated by Django 4.1.13 on 2025-04-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0002_predictionresult'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='predictionresult',
            table='prediction_resuls',
        ),
        migrations.AlterModelTable(
            name='uploadedimage',
            table='uploaded_images',
        ),
    ]
