# Generated by Django 4.1.13 on 2025-04-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0003_alter_predictionresult_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='predictionresult',
            table='prediction_results',
        ),
    ]
