# Generated by Django 5.2 on 2025-05-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0006_predictionresult_user_uploadedimage_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='imageProfile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disease_detection.customuser'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='predicted_disease',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disease_detection.customuser'),
        ),
    ]
