# Generated by Django 5.2 on 2025-05-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0007_alter_predictionresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
