# Generated by Django 5.2 on 2025-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0009_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
